### ISSUE TITLE
now it should be possible with blocks

### ISSUE THREAD

**Issue by elibyy** [Vinai/phpstorm-magento-mapper#3]
the new phpstorm 9 should provide that
https://youtrack.jetbrains.com/issue/WI-27712#tab=Comments

**Comment by Vinai** [comment]
I'm always surprised anybody still uses the script from this repository, given that magicento seems like the industry standard for making PHPStorm know more about Magento internals. :)
Anyway, thanks for notifying me. I'll won't be doing any updates, but if you send a PR I'll be happy to merge.
